// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gamefee_manager.proto

package gamefee_manager

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReturnGameFeeRequest struct {
	ChainId              int64    `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	CrossTxId            int64    `protobuf:"varint,3,opt,name=cross_tx_id,json=crossTxId,proto3" json:"cross_tx_id,omitempty"`
	TossId               int64    `protobuf:"varint,4,opt,name=toss_id,json=tossId,proto3" json:"toss_id,omitempty"`
	TokenName            string   `protobuf:"bytes,5,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnGameFeeRequest) Reset()         { *m = ReturnGameFeeRequest{} }
func (m *ReturnGameFeeRequest) String() string { return proto.CompactTextString(m) }
func (*ReturnGameFeeRequest) ProtoMessage()    {}
func (*ReturnGameFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01db16f4eed4abab, []int{0}
}

func (m *ReturnGameFeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnGameFeeRequest.Unmarshal(m, b)
}
func (m *ReturnGameFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnGameFeeRequest.Marshal(b, m, deterministic)
}
func (m *ReturnGameFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnGameFeeRequest.Merge(m, src)
}
func (m *ReturnGameFeeRequest) XXX_Size() int {
	return xxx_messageInfo_ReturnGameFeeRequest.Size(m)
}
func (m *ReturnGameFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnGameFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnGameFeeRequest proto.InternalMessageInfo

func (m *ReturnGameFeeRequest) GetChainId() int64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *ReturnGameFeeRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ReturnGameFeeRequest) GetCrossTxId() int64 {
	if m != nil {
		return m.CrossTxId
	}
	return 0
}

func (m *ReturnGameFeeRequest) GetTossId() int64 {
	if m != nil {
		return m.TossId
	}
	return 0
}

func (m *ReturnGameFeeRequest) GetTokenName() string {
	if m != nil {
		return m.TokenName
	}
	return ""
}

type ReturnGameFeeResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnGameFeeResponse) Reset()         { *m = ReturnGameFeeResponse{} }
func (m *ReturnGameFeeResponse) String() string { return proto.CompactTextString(m) }
func (*ReturnGameFeeResponse) ProtoMessage()    {}
func (*ReturnGameFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01db16f4eed4abab, []int{1}
}

func (m *ReturnGameFeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnGameFeeResponse.Unmarshal(m, b)
}
func (m *ReturnGameFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnGameFeeResponse.Marshal(b, m, deterministic)
}
func (m *ReturnGameFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnGameFeeResponse.Merge(m, src)
}
func (m *ReturnGameFeeResponse) XXX_Size() int {
	return xxx_messageInfo_ReturnGameFeeResponse.Size(m)
}
func (m *ReturnGameFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnGameFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnGameFeeResponse proto.InternalMessageInfo

func (m *ReturnGameFeeResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type ClaimGameFeeRequest struct {
	ChainId              int64    `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Amount               string   `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	TxHash               string   `protobuf:"bytes,5,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TxTime               string   `protobuf:"bytes,6,opt,name=tx_time,json=txTime,proto3" json:"tx_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClaimGameFeeRequest) Reset()         { *m = ClaimGameFeeRequest{} }
func (m *ClaimGameFeeRequest) String() string { return proto.CompactTextString(m) }
func (*ClaimGameFeeRequest) ProtoMessage()    {}
func (*ClaimGameFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01db16f4eed4abab, []int{2}
}

func (m *ClaimGameFeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClaimGameFeeRequest.Unmarshal(m, b)
}
func (m *ClaimGameFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClaimGameFeeRequest.Marshal(b, m, deterministic)
}
func (m *ClaimGameFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimGameFeeRequest.Merge(m, src)
}
func (m *ClaimGameFeeRequest) XXX_Size() int {
	return xxx_messageInfo_ClaimGameFeeRequest.Size(m)
}
func (m *ClaimGameFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimGameFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimGameFeeRequest proto.InternalMessageInfo

func (m *ClaimGameFeeRequest) GetChainId() int64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *ClaimGameFeeRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ClaimGameFeeRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ClaimGameFeeRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *ClaimGameFeeRequest) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *ClaimGameFeeRequest) GetTxTime() string {
	if m != nil {
		return m.TxTime
	}
	return ""
}

type ClaimGameFeeResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClaimGameFeeResponse) Reset()         { *m = ClaimGameFeeResponse{} }
func (m *ClaimGameFeeResponse) String() string { return proto.CompactTextString(m) }
func (*ClaimGameFeeResponse) ProtoMessage()    {}
func (*ClaimGameFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01db16f4eed4abab, []int{3}
}

func (m *ClaimGameFeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClaimGameFeeResponse.Unmarshal(m, b)
}
func (m *ClaimGameFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClaimGameFeeResponse.Marshal(b, m, deterministic)
}
func (m *ClaimGameFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimGameFeeResponse.Merge(m, src)
}
func (m *ClaimGameFeeResponse) XXX_Size() int {
	return xxx_messageInfo_ClaimGameFeeResponse.Size(m)
}
func (m *ClaimGameFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimGameFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimGameFeeResponse proto.InternalMessageInfo

func (m *ClaimGameFeeResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ClaimGameFeeResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ReturnGameFeeRequest)(nil), "gamefee_manager.api.ReturnGameFeeRequest")
	proto.RegisterType((*ReturnGameFeeResponse)(nil), "gamefee_manager.api.ReturnGameFeeResponse")
	proto.RegisterType((*ClaimGameFeeRequest)(nil), "gamefee_manager.api.ClaimGameFeeRequest")
	proto.RegisterType((*ClaimGameFeeResponse)(nil), "gamefee_manager.api.ClaimGameFeeResponse")
}

func init() { proto.RegisterFile("gamefee_manager.proto", fileDescriptor_01db16f4eed4abab) }

var fileDescriptor_01db16f4eed4abab = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xbd, 0x4e, 0xeb, 0x40,
	0x10, 0x85, 0xaf, 0xf3, 0xe3, 0x5c, 0xcf, 0xbd, 0x44, 0x68, 0xe2, 0x80, 0x89, 0x04, 0x8a, 0x5c,
	0x25, 0x14, 0x8e, 0x04, 0x25, 0x54, 0x20, 0x01, 0x29, 0xa0, 0xb0, 0x52, 0xd1, 0x58, 0x8b, 0x3d,
	0xc4, 0x16, 0xac, 0x37, 0x78, 0xd7, 0x92, 0x5f, 0x85, 0x57, 0xe0, 0xad, 0x78, 0x13, 0xe4, 0xcd,
	0x46, 0x22, 0x91, 0x8b, 0x74, 0x7b, 0x66, 0xce, 0x78, 0xbf, 0xe3, 0x59, 0x18, 0x2e, 0x19, 0xa7,
	0x57, 0xa2, 0x88, 0xb3, 0x9c, 0x2d, 0xa9, 0x08, 0x56, 0x85, 0x50, 0x02, 0x07, 0xbb, 0x65, 0xb6,
	0xca, 0xfc, 0x4f, 0x0b, 0xdc, 0x90, 0x54, 0x59, 0xe4, 0xf7, 0x8c, 0xd3, 0x1d, 0x51, 0x48, 0x1f,
	0x25, 0x49, 0x85, 0x27, 0xf0, 0x37, 0x4e, 0x59, 0x96, 0x47, 0x59, 0xe2, 0x59, 0x63, 0x6b, 0xd2,
	0x0e, 0x7b, 0x5a, 0xcf, 0x13, 0xec, 0x43, 0x4b, 0x09, 0xaf, 0x35, 0xb6, 0x26, 0x4e, 0xd8, 0x52,
	0x02, 0xcf, 0xe0, 0x5f, 0x5c, 0x08, 0x29, 0x23, 0x55, 0xd5, 0xee, 0xb6, 0x76, 0x3b, 0xba, 0xb4,
	0xa8, 0xe6, 0x09, 0x1e, 0x43, 0x4f, 0xd5, 0xed, 0x2c, 0xf1, 0x3a, 0xba, 0x67, 0xd7, 0x72, 0x9e,
	0xe0, 0x29, 0x80, 0x12, 0x6f, 0x94, 0x47, 0x39, 0xe3, 0xe4, 0x75, 0xf5, 0x07, 0x1d, 0x5d, 0x79,
	0x62, 0x9c, 0xfc, 0x19, 0x0c, 0x77, 0xd0, 0xe4, 0x4a, 0xe4, 0x92, 0xf0, 0x08, 0x6c, 0xa9, 0x98,
	0x2a, 0xa5, 0x21, 0x33, 0xca, 0xff, 0xb2, 0x60, 0x70, 0xfb, 0xce, 0x32, 0xbe, 0x7f, 0x16, 0x0f,
	0x7a, 0x2c, 0x8e, 0x45, 0x99, 0x2b, 0x13, 0x68, 0x23, 0xd1, 0x85, 0xae, 0x46, 0xd1, 0x79, 0x9c,
	0x70, 0x2d, 0xea, 0xab, 0x19, 0xd7, 0xf6, 0x8e, 0x2e, 0x1b, 0xa5, 0x33, 0x56, 0x51, 0xca, 0x64,
	0x6a, 0x72, 0xd8, 0xaa, 0x7a, 0x60, 0x32, 0x35, 0x0d, 0x95, 0x71, 0xf2, 0xec, 0x4d, 0x63, 0x91,
	0x71, 0xf2, 0xaf, 0xc1, 0xdd, 0x66, 0x35, 0xe1, 0x10, 0x3a, 0xb1, 0x48, 0x48, 0x83, 0x3a, 0xa1,
	0x3e, 0xe3, 0x21, 0xb4, 0xb9, 0x5c, 0x1a, 0xc2, 0xfa, 0x78, 0xf1, 0x6d, 0x41, 0xdf, 0x4c, 0x3e,
	0xae, 0xd7, 0x89, 0x29, 0x1c, 0x6c, 0xfd, 0x2e, 0x9c, 0x06, 0x0d, 0x1b, 0x0f, 0x9a, 0xb6, 0x3d,
	0x3a, 0xdf, 0xc7, 0xba, 0x06, 0xf4, 0xff, 0x20, 0xc1, 0xff, 0xdf, 0xe8, 0x38, 0x69, 0x9c, 0x6e,
	0xd8, 0xc4, 0x68, 0xba, 0x87, 0x73, 0x73, 0xcd, 0x8d, 0xfb, 0x8c, 0xc1, 0xec, 0x6a, 0x67, 0xe0,
	0xc5, 0xd6, 0xaf, 0xf9, 0xf2, 0x27, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xac, 0x96, 0xf6, 0xe6, 0x02,
	0x00, 0x00,
}
